In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Numpy merupakan library  phyton digunakan untuk kompotasi matriks. Matplotlib merupakan library phyton untuk presentasi data berupa grafik atau plot . . . .. 

In [ ]:
dataset = pd.read_csv('Dataset.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [18]:
print (x)
print (y)

[[1.0 0.0 1.0 0.0 49.0 86400.0]
 [0.0 1.0 0.0 0.0 32.0 57600.0]
 [1.0 0.0 0.0 1.0 35.0 64800.0]
 [0.0 1.0 0.0 0.0 43.0 73200.0]
 [1.0 0.0 0.0 1.0 45.0 76533.33333333333]
 [1.0 0.0 1.0 0.0 40.0 69600.0]
 [0.0 1.0 0.0 0.0 43.77777777777778 62400.0]
 [1.0 0.0 1.0 0.0 53.0 94800.0]
 [1.0 0.0 0.0 1.0 55.0 99600.0]
 [1.0 0.0 1.0 0.0 42.0 80400.0]]
[1 1 0 0 1 0 0 1 0 1]


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [19]:
print (x)

[[1.0 0.0 1.0 0.0 49.0 86400.0]
 [0.0 1.0 0.0 0.0 32.0 57600.0]
 [1.0 0.0 0.0 1.0 35.0 64800.0]
 [0.0 1.0 0.0 0.0 43.0 73200.0]
 [1.0 0.0 0.0 1.0 45.0 76533.33333333333]
 [1.0 0.0 1.0 0.0 40.0 69600.0]
 [0.0 1.0 0.0 0.0 43.77777777777778 62400.0]
 [1.0 0.0 1.0 0.0 53.0 94800.0]
 [1.0 0.0 0.0 1.0 55.0 99600.0]
 [1.0 0.0 1.0 0.0 42.0 80400.0]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [20]:
print (x)

[[1.0 0.0 1.0 0.0 49.0 86400.0]
 [0.0 1.0 0.0 0.0 32.0 57600.0]
 [1.0 0.0 0.0 1.0 35.0 64800.0]
 [0.0 1.0 0.0 0.0 43.0 73200.0]
 [1.0 0.0 0.0 1.0 45.0 76533.33333333333]
 [1.0 0.0 1.0 0.0 40.0 69600.0]
 [0.0 1.0 0.0 0.0 43.77777777777778 62400.0]
 [1.0 0.0 1.0 0.0 53.0 94800.0]
 [1.0 0.0 0.0 1.0 55.0 99600.0]
 [1.0 0.0 1.0 0.0 42.0 80400.0]]


In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [21]:
print (y)

[1 1 0 0 1 0 0 1 0 1]


In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 1)

In [22]:
print (x_train)

[[0.0 1.0 0.0 -0.5773502691896258 -0.19159184384578545 -1.078125940841242]
 [1.0 0.0 0.0 1.7320508075688774 -0.014117293757057777
  -0.07013167641635393]
 [1.0 0.0 1.0 -0.5773502691896258 0.566708506533324 0.6335624327104554]
 [0.0 1.0 0.0 -0.5773502691896258 -0.30453019390224867
  -0.30786617274297823]
 [0.0 1.0 0.0 -0.5773502691896258 -1.9018011447007988 -1.4204636155515815]
 [1.0 0.0 1.0 -0.5773502691896258 1.1475343068237058 1.2326533634535495]
 [1.0 0.0 0.0 1.7320508075688774 1.4379472069688968 1.574991038163889]
 [1.0 0.0 1.0 -0.5773502691896258 -0.7401495441200351 -0.5646194287757329]]


In [23]:
print (x_test)

[[1.0 0.0 0.0 1.7320508075688774 -1.4661817944830124 -0.9069571034860724]
 [1.0 0.0 1.0 -0.5773502691896258 -0.44973664397484414 0.205640339322531]]


In [24]:
print (y_train)

[0 1 1 0 1 1 0 0]


In [15]:
print (y_test)

[0 1]


In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train [:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [26]:
print(x_train)

[[0.0 1.0 0.0 -0.5773502691896258 -0.1915918438457856 -1.0781259408412427]
 [1.0 0.0 0.0 1.7320508075688774 -0.014117293757057902
  -0.0701316764163546]
 [1.0 0.0 1.0 -0.5773502691896258 0.5667085065333239 0.6335624327104548]
 [0.0 1.0 0.0 -0.5773502691896258 -0.3045301939022488 -0.3078661727429789]
 [0.0 1.0 0.0 -0.5773502691896258 -1.901801144700799 -1.4204636155515822]
 [1.0 0.0 1.0 -0.5773502691896258 1.1475343068237056 1.2326533634535488]
 [1.0 0.0 0.0 1.7320508075688774 1.4379472069688966 1.5749910381638883]
 [1.0 0.0 1.0 -0.5773502691896258 -0.7401495441200352 -0.5646194287757336]]
